const http = require('node:http');
const { URL } = require('node:url');
const crypto = require('node:crypto');

const PORT = Number(process.env.PORT || 7002);
const PUBLIC_BASE_URL = (process.env.PUBLIC_BASE_URL || `http://127.0.0.1:${PORT}`).replace(/\/$/, '');
const GEMINI_API_KEY = String(process.env.GEMINI_API_KEY || '').trim();
const GEMINI_MODEL = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
const OPEN_SUBTITLES_API_KEY = String(process.env.OPENSUBTITLES_API_KEY || '').trim();
const cache = new Map();

function json(res, status, body) { const data = JSON.stringify(body); res.writeHead(status, {'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'no-store'}); res.end(data); }
function text(res, status, body, type='text/plain; charset=utf-8') { res.writeHead(status, {'content-type':type,'access-control-allow-origin':'*','cache-control':'no-store'}); res.end(body); }
function manifest() { return {id:'com.stremio.slo.ai.translator',version:'0.1.0',name:'Slo AI Subtitle Translator',description:'Metadata-aware English to Slovenian subtitles with strict gender consistency and SRT validation.',logo:`${PUBLIC_BASE_URL}/logo.svg`,resources:['subtitles'],types:['movie','series'],idPrefixes:['tt'],catalogs:[],behaviorHints:{configurable:true,configurationRequired:true}}; }
function configurePage() { return `<!doctype html><meta charset="utf-8"><title>Slo AI Subtitle Translator</title><h1>Slo AI Subtitle Translator</h1><p>Set the API keys on the server, then install the generated manifest.</p><p>Manifest: <code>${PUBLIC_BASE_URL}/manifest.json</code></p>`; }
function srtEntries(srt) { return String(srt).replace(/\r/g,'').trim().split(/\n\s*\n/).filter(Boolean).map(block=>{const lines=block.split('\n'); const time=lines.findIndex(x=>x.includes('-->')); if(time<1) return null; return {id:lines[0].trim(),timecode:lines[time].trim(),text:lines.slice(time+1).join('\n')};}).filter(Boolean); }
function validateSrt(original, translated) { const a=srtEntries(original), b=srtEntries(translated); if(!a.length || a.length!==b.length) return false; return a.every((x,i)=>x.id===b[i].id && x.timecode===b[i].timecode && b[i].text.trim()); }
function buildPrompt({title='Unknown title',plot='Not provided',characters='Not provided',source,speakerMemory='Not provided'}) { return `You are a professional subtitle translator specializing in English to Slovenian translation.\n\nMOVIE CONTEXT & METADATA\n- Movie Title: ${title}\n- Plot Summary: ${plot}\n- Main Characters & Genders:\n${characters}\n- Stable Speaker/Character Ledger:\n${speakerMemory}\n\nSTRICT TRANSLATION RULES\n1. Identify who is speaking from metadata, dialogue flow and stable ledger. Never infer gender from voice alone. Distinguish speaker gender from addressee gender.\n2. Female first-person forms: bila sem, šla sem, rekla sem, vesela sem. Male: bil sem, šel sem, rekel sem, vesel sem.\n3. Correct second-person forms: si videla/videl, pripravljena/pripravljen. Check every gendered verb, adjective, pronoun and agreement across adjacent cues. If evidence is insufficient, do not invent a gendered fact; use natural wording that avoids unsupported gender.\n4. Preserve every SRT number and timestamp character-for-character, cue order, block count, formatting and line breaks. Never merge, split, delete or reorder cues.\n5. Use natural conversational Slovenian, consistent informal/formal address and terminology.\n\nReturn ONLY valid translated SRT. No notes, explanations or markdown.\n\nINPUT SUBTITLES:\n${source}`; }
async function gemini(prompt) { if(!GEMINI_API_KEY) throw new Error('GEMINI_API_KEY is not configured'); const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${encodeURIComponent(GEMINI_API_KEY)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:0.15,responseMimeType:'text/plain'}})}); if(!r.ok) throw new Error(`Gemini HTTP ${r.status}`); const d=await r.json(); return d.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('').replace(/^```(?:srt|text)?\s*/i,'').replace(/\s*```$/,'').trim() || ''; }
async function metadata(id) { try { const r=await fetch(`https://v3-cinemeta.strem.io/meta/movie/${encodeURIComponent(id)}.json`); if(!r.ok)return {}; const d=await r.json(); const m=d.meta||{}; return {title:m.name||id,plot:m.description||'Not provided',characters:(m.cast||[]).map(x=>`${x.name}: gender unknown`).join('\n')||'Not provided'}; } catch { return {title:id}; } }
async function sourceSubtitle(id) { if(!OPEN_SUBTITLES_API_KEY) throw new Error('OPENSUBTITLES_API_KEY is not configured'); const r=await fetch(`https://api.opensubtitles.com/api/v1/subtitles?languages=en&order_by=downloads&order_direction=desc&imdb_id=${encodeURIComponent(String(id).replace(/^tt/,''))}`,{headers:{'Api-Key':OPEN_SUBTITLES_API_KEY,'User-Agent':'SloAIAddon v0.1.0','Accept':'application/json'}}); if(!r.ok)throw new Error(`OpenSubtitles HTTP ${r.status}`); const d=await r.json(); const file=d.data?.[0]?.attributes?.files?.[0]; if(!file?.file_id)throw new Error('No English subtitle found'); const q=await fetch('https://api.opensubtitles.com/api/v1/download',{method:'POST',headers:{'Api-Key':OPEN_SUBTITLES_API_KEY,'User-Agent':'SloAIAddon v0.1.0','content-type':'application/json'},body:JSON.stringify({file_id:file.file_id})}); if(!q.ok)throw new Error(`OpenSubtitles download HTTP ${q.status}`); const j=await q.json(); if(!j.link)throw new Error('OpenSubtitles returned no download link'); const s=await fetch(j.link); if(!s.ok)throw new Error('Subtitle download failed'); return s.text(); }
async function handleSubtitle(type,id) { const key=crypto.createHash('sha256').update(`${type}:${id}:sl:${GEMINI_MODEL}`).digest('hex'); if(cache.has(key)) return cache.get(key); const source=await sourceSubtitle(id); const meta=await metadata(id); const translated=await gemini(buildPrompt({...meta,source})); if(!validateSrt(source,translated)) throw new Error('Translator returned invalid SRT structure'); cache.set(key,translated); return translated; }
function handler(req,res) { const u=new URL(req.url,`http://${req.headers.host||'localhost'}`); if(req.method==='GET'&&u.pathname==='/manifest.json')return json(res,200,manifest()); if(req.method==='GET'&&u.pathname==='/manifest')return json(res,200,manifest()); if(req.method==='GET'&&u.pathname==='/configure')return text(res,200,configurePage(),'text/html; charset=utf-8'); if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{status:'healthy',cacheEntries:cache.size,geminiConfigured:Boolean(GEMINI_API_KEY),openSubtitlesConfigured:Boolean(OPEN_SUBTITLES_API_KEY)}); const m=u.pathname.match(/^\/subtitles\/(movie|series)\/([^/]+)(?:\/.*)?\.json$/); if(req.method==='GET'&&m){handleSubtitle(m[1],decodeURIComponent(m[2])).then(s=>json(res,200,{subtitles:[{id:'slo-ai',url:`data:text/plain;charset=utf-8,${encodeURIComponent(s)}`,lang:'sl',label:'Slovenian AI'}]})).catch(e=>json(res,200,{subtitles:[],error:e.message}));return;} json(res,404,{error:'Not found'}); }
if(require.main===module) http.createServer(handler).listen(PORT,'0.0.0.0',()=>console.log(`Slo AI addon listening on ${PORT}`));
module.exports={buildPrompt,srtEntries,validateSrt,manifest,handler};
